EcommerceMVC/Controllers/CartController.cs
using EcommerceMVC.Data;
using EcommerceMVC.Helpers;
using EcommerceMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceMVC.Controllers
{
	public class CartController : Controller
	{
		private readonly Hshop2023Context db;

		public CartController(Hshop2023Context context)
		{
			db = context;
		}

		const string CART_KEY = "MYCART";
		public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(MySetting.CART_KEY) ?? new List<CartItem>();

		public IActionResult Index()
		{
			return View(Cart);
		}

		public IActionResult AddToCart(int id, int quantity = 1)
		{
			var gioHang = Cart;
			var item = gioHang.SingleOrDefault(p => p.MaHh == id);
			if (item == null)
			{
				var hangHoa = db.HangHoas.SingleOrDefault(p => p.MaHh == id);
				if (hangHoa == null)
				{
					TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
					return Redirect("/404");
				}
				item = new CartItem
				{
					MaHh = hangHoa.MaHh,
					TenHH = hangHoa.TenHh,
					DonGia = hangHoa.DonGia ?? 0,
					Hinh = hangHoa.Hinh ?? string.Empty,
					SoLuong = quantity
				};
				gioHang.Add(item);
			}
			else
			{
				item.SoLuong += quantity;
			}

			HttpContext.Session.Set(MySetting.CART_KEY, gioHang);

			return RedirectToAction("Index");
		}

		public IActionResult RemoveCart(int id)
		{
			var gioHang = Cart;
			var item = gioHang.SingleOrDefault(p => p.MaHh == id);
			if (item != null)
			{
				gioHang.Remove(item);
				HttpContext.Session.Set(MySetting.CART_KEY, gioHang);
			}
			return RedirectToAction("Index");
		}
	}
}

EcommerceMVC/Controllers/HangHoaController.cs
using EcommerceMVC.Data;
using EcommerceMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EcommerceMVC.Models;
using PagedList;

namespace EcommerceMVC.Controllers
{
	public class HangHoaController : Controller
	{
        private readonly Hshop2023Context db; //readonly chỉ đc gán giá trị 1 lần

		public HangHoaController(Hshop2023Context conetxt) //
        {
            db = conetxt; //giúp db truy vấn dữ liệu
        }

        public IActionResult Index(int? loai)
        {
            var hangHoas = db.HangHoas.AsQueryable();

            if (loai.HasValue)
            {
                hangHoas = hangHoas.Where(p => p.MaLoai == loai.Value);
            }

            var result = hangHoas.Select(p => new HangHoaVM
            {
                MaHh = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                TenLoai = p.MaLoaiNavigation.TenLoai
            });
            return View(result);
        }

        public IActionResult Search(string? query)
        {
            var hangHoas = db.HangHoas.AsQueryable();

            if (query != null)
            {
                hangHoas = hangHoas.Where(p => p.TenHh.Contains(query));
            }

            var result = hangHoas.Select(p => new HangHoaVM
            {
                MaHh = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                TenLoai = p.MaLoaiNavigation.TenLoai
            });
            return View(result);
        }
        public IActionResult Detail(int id)
        {
            var data = db.HangHoas
                .Include(p => p.MaLoaiNavigation)
                .SingleOrDefault(p => p.MaHh == id);
            if (data == null)
            {
                TempData["Message"] = $"Không thấy sản phẩm có mã {id}";
                return Redirect("/404");
            }

            var result = new ChiTietHangHoaVM
            {
                MaHh = data.MaHh,
                TenHH = data.TenHh,
                DonGia = data.DonGia ?? 0,
                ChiTiet = data.MoTa ?? string.Empty,
                Hinh = data.Hinh ?? string.Empty,
                MoTaNgan = data.MoTaDonVi ?? string.Empty,
                TenLoai = data.MaLoaiNavigation.TenLoai,
                SoLuongTon = 10,
                DiemDanhGia = 5,
            };
            return View(result);
        }

        public IActionResult DanhMucSanPham(int page = 1, int pageSize = 10)
        {
            var danhSachHangHoa = db.HangHoas.ToList(); // Lấy dữ liệu từ CSDL
            var pagedList = danhSachHangHoa.ToPagedList(page, pageSize); // Chuyển thành IPagedList
            return View(pagedList); // Trả về view với IPagedList
        }
    }
}

EcommerceMVC/ViewComponents/MenuLoaiViewComponent.cs
using EcommerceMVC.Data;
using EcommerceMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceMVC.Viewcomponents
{
    public class MenuLoaiViewComponent : ViewComponent
    {
        private readonly Hshop2023Context db;

        public MenuLoaiViewComponent(Hshop2023Context context) => db = context;

        public IViewComponentResult Invoke()
        {
            var data = db.Loais.Select(lo => new MenuLoaiVM
            {
                MaLoai = lo.MaLoai,
                TenLoai = lo.TenLoai,
                SoLuong = lo.HangHoas.Count
            }).OrderBy(p => p.TenLoai);   

			return View(data); 
        }
    }
}

EcommerceMVC/Views/Shared/_Copyright.cshtml
<!-- Copyright Start -->
<div class="container-fluid copyright bg-dark py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>Your Site Name</a>, All right reserved.</span>
            </div>
            <div class="col-md-6 my-auto text-center text-md-end text-white">
                <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
            </div>
        </div>
    </div>
</div>
<!-- Copyright End -->

EcommerceMVC/Views/Shared/_DanhSachHangHoa.cshtml
@{
    Layout="_LayoutCustomer"; //Xác định layout chung
}
<!-- Single Page Header start -->
<!-- Single Page Header start -->
@RenderSection("BreadCum", required: false) @* BreadCum: tên section và section này không bắt buộc *@
<!-- Single Page Header End -->
<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
	<div class="container py-5">
		<h1 class="mb-4">TLSHOP</h1>
		<div class="row g-4">
			<div class="col-lg-12">
				<div class="row g-4">
					<div class="col-xl-3">
						@await Html.PartialAsync("_TimKiemPanel")  @* Render một Partial View, *@
						@* Render: Là quá trình chuyển dữ liệu động từ Controller/Model thành HTML tĩnh để hiển thị cho người dùng. *@
					</div>
					<div class="col-6"></div>
					<div class="col-xl-3">

					</div>
				</div>
				<div class="row g-4">
					<div class="col-lg-3">
						<div class="row g-4">
							@await Component.InvokeAsync("MenuLoai")

							
							
							<div class="col-lg-12">
								<h4 class="mb-3">Sản phẩm nôi bật</h4>
								<div class="d-flex align-items-center justify-content-start">
									<div class="rounded me-4" style="width: 100px; height: 100px;">
										<img src="~/img/dautay3.jpg" class="img-fluid rounded" alt="">
									</div>
									<div>
										<h6 class="mb-2">Dâu Tây</h6>
										<div class="d-flex mb-2">
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star"></i>
										</div>
										<div class="d-flex mb-2">
											<h5 class="fw-bold me-2">₫69.000</h5>
											<h5 class="text-danger text-decoration-line-through">₫80.000</h5>
										</div>
									</div>
								</div>
								<div class="d-flex align-items-center justify-content-start">
									<div class="rounded me-4" style="width: 100px; height: 100px;">
										<img src="~/img/macca.jpg" class="img-fluid rounded" alt="">
									</div>
									<div>
										<h6 class="mb-2">Macca</h6>
										<div class="d-flex mb-2">
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star"></i>
										</div>
										<div class="d-flex mb-2">
											<h5 class="fw-bold me-2">₫89.000</h5>
											<h5 class="text-danger text-decoration-line-through">₫99.000</h5>
										</div>
									</div>
								</div>
								<div class="d-flex align-items-center justify-content-start">
									<div class="rounded me-4" style="width: 100px; height: 100px;">
										<img src="~/img/nuocepdt.jpg" class="img-fluid rounded" alt="">
									</div>
									<div>
										<h6 class="mb-2">Nước ép dâu tằm</h6>
										<div class="d-flex mb-2">
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star text-secondary"></i>
											<i class="fa fa-star"></i>
										</div>
										<div class="d-flex mb-2">
											<h5 class="fw-bold me-2">₫59.000</h5>
											<h5 class="text-danger text-decoration-line-through">₫79.000</h5>
										</div>
									</div>
								</div>
								<div class="d-flex justify-content-center my-4">
									<a href="#" class="btn border border-secondary px-4 py-3 rounded-pill text-primary w-100">Vew More</a>
								</div>
							</div>
							<div class="col-lg-12">
								<div class="position-relative">
									<img src="~/img/hong-treo-gio-dalavi-dalat.jpg" class="img-fluid w-100 rounded" alt="">
									<div class="position-absolute" style="top: 50%; right: 10px; transform: translateY(-50%);">
										<h3 class="text-secondary fw-bold">Đặc <br> Biệt</h3>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						<div class="row g-4 justify-content-center">
							@RenderBody()
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Fruits Shop End-->			

EcommerceMVC/Views/Shared/_Footer.cshtml
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
    <div class="container py-5">
        <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
            <div class="row g-4">
                <div class="col-lg-3">
                    <a href="#">
                        <h1 class="text-primary mb-0">Đặc sản Đà Lạt</h1>
                       
                    </a>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative mx-auto">
                        <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number" placeholder="Nhập email của bạn">
                        <button type="submit" class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white" style="top: 0; right: 0;">Tìm kiếm</button>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="d-flex justify-content-end pt-3">
                        <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Tại sao bạn nên chọn chúng tôi!</h4>
                    <p class="mb-4">
                        Mua đặc sản Đà Lạt ở chỗ bạn không chỉ mang lại những sản phẩm chất lượng mà còn là trải nghiệm 
                        thú vị cho khách hàng!
                    </p>
                    <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Đọc thêm</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Thông tin cửa hàng</h4>
                    <a class="btn-link" href="">Giới thiệu chúng tôi</a>
                    <a class="btn-link" href="">Liên hệ với chúng tôi</a>
                    <a class="btn-link" href="">Chính sách bảo mật</a>
                    <a class="btn-link" href="">Trợ giúp</a>
      
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Tài khoản</h4>
                    <a class="btn-link" href="">Tài khoản của tôi</a>
                    <a class="btn-link" href="">Chi tiết cửa hàng</a>
                    <a class="btn-link" href="">Giỏ hàng</a>
                    <a class="btn-link" href="">Danh sách sản phẩm</a>
                   
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Liên lạc</h4>
                    <p>Địa chỉ: 1 Phù Đổng Thiên Vương, Phường 8 Đà Lạt</p>
                   <p>Email:</p>
                    <p>2212399@dlu.edu.vn.com</p>
                    <p>2212483@dlu.edu.vn</p>
                    

                    <p>Điện thoại: +0123 4567 8910</p>
                    <p>Thanh toán bằng:</p>
                    <img src="img/payment.png" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

EcommerceMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EcommerceMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EcommerceMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EcommerceMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EcommerceMVC/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<meta charset="utf-8">
	<meta content="" name="keywords">
	<meta content="" name="description">

	<!-- Google Web Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">

	<!-- Icon Font Stylesheet -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

	<!-- Libraries Stylesheet -->
	<link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
	<link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


	<!-- Customized Bootstrap Stylesheet -->
	<link href="~/css/bootstrap.min.css" rel="stylesheet">

	<!-- Template Stylesheet -->
	<link href="~/css/style.css" rel="stylesheet">
	@RenderSection("Styles", required: false)
</head>
<body>
	<div>
		<!-- Spinner Start -->
		<div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
			<div class="spinner-grow text-primary" role="status"></div>
		</div>
		<!-- Spinner End -->
		<!-- Navbar start -->
		<div class="container-fluid fixed-top">
			<div class="container topbar bg-primary d-none d-lg-block">
				<div class="d-flex justify-content-between">
					<div class="top-info ps-2">
						<small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">Address: 01 Phù Đổng Thiên Vương, Tp. Đà Lạt, Lâm Đồng</a></small>
						<small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email: phongtchc@dlu.edu.vn</a></small>
					</div>
					<div class="top-link pe-2">
						<a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
						<a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
						<a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
					</div>
				</div>
			</div>
			<div class="container px-0">
				<nav class="navbar navbar-light bg-white navbar-expand-xl">
					<a asp-action="Index" asp-controller="Home" class="navbar-brand"><h1 class="text-primary display-6">Đặc sản Đà Lạt</h1></a>
					<button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
						<span class="fa fa-bars text-primary"></span>
					</button>
					<div class="collapse navbar-collapse bg-white" id="navbarCollapse">
						<div class="navbar-nav mx-auto">
							<a asp-action="Index" asp-controller="Home" class="nav-item nav-link active">Trang chủ</a>
							<a asp-controller="HangHoa" asp-action="Index" class="nav-item nav-link">Cửa hàng</a>
							<div class="nav-item dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Thành viên</a>
								<div class="dropdown-menu m-0 bg-secondary rounded-0">
									<a asp-controller="Cart" asp-action="Index" class="dropdown-item">Giỏ hàng</a>
									@if (User.Identity.IsAuthenticated)
									{
										<a asp-controller="Home" asp-action="Profile" class="dropdown-item">Thông tin tài khoản</a>
										<a asp-controller="Home" asp-action="DangXuat" class="dropdown-item">Đăng xuất</a>
									}
									else
									{
										<a asp-controller="Home" asp-action="DangKy" class="dropdown-item">Đăng ký</a>
										<a asp-controller="Home" asp-action="DangNhap" class="dropdown-item">Đăng nhập</a>
										<a asp-controller="Home" asp-action="QuenMatKhau" class="dropdown-item">Quên mật khẩu</a>
									}
								</div>
							</div>
							<a asp-controller="LienHe" asp-action="Index" class="nav-item nav-link">Liên hệ</a>
							@if (User.IsInRole("Admin"))
							{
								<a asp-controller="Admin" asp-action="Index" class="nav-item nav-link">Trang quản trị</a>
							}
						</div>
						<div class="d-flex m-3 me-0">
							<button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>

							@await Component.InvokeAsync("Cart")

							<a asp-action="DangNhap" asp-controller="Home" class="my-auto" title="Đăng nhập">
								<i class="fas fa-user fa-2x"></i>
							</a>
						</div>
					</div>
				</nav>
			</div>
		</div>
		<!-- Navbar End -->
		<!-- Modal Search Start -->
		<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-fullscreen">
				<div class="modal-content rounded-0">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body d-flex align-items-center">
						<div class="input-group w-75 mx-auto d-flex">
							<input id="searchText" type="search" class="form-control p-3" placeholder="keywords" aria-describedby="seachButton">
							<span id="seachButton" class="input-group-text p-3"><i class="fa fa-search"></i></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Modal Search End -->

		<div style="min-height:400px;" class="hero-header">
			@RenderBody()
		</div>



		@await Html.PartialAsync("_Footer")

		@await Html.PartialAsync("_Copyright")
	</div>

	<!-- Back to Top -->
	<a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>


	<!-- JavaScript Libraries -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/easing/easing.min.js"></script>
	<script src="~/lib/waypoints/waypoints.min.js"></script>
	<script src="~/lib/lightbox/js/lightbox.min.js"></script>
	<script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

	<!-- Template Javascript -->
	<script src="~/js/main.js"></script>
	@RenderSection("Scripts", required: false)

	<script>
		$(document).ready(function () {
			$("#seachButton").click(function () {
				let url = `/HangHoa/Search?query=` + $("#searchText").val();
				window.location.href = url;
			});
		});
	</script>
</body>
</html>

EcommerceMVC/Views/Shared/_TimKiemPanel.cshtml
<form name="SearchForm" asp-action="Search" asp-controller="HangHoa">
	<div class="input-group w-100 mx-auto d-flex">
		<input type="search" class="form-control p-3" placeholder="Từ khóa" aria-describedby="searchButton" name="query" id="searchText">
		<span id="searchButton" class="input-group-text p-3" onclick="SearchForm.submit()"><i class="fa fa-search"></i></span>
	</div>
</form>